// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaginationMvcApp.Data;

#nullable disable

namespace PaginationMvcApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .UseIdentityColumns();

            modelBuilder.Entity("PaginationMvcApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Name = "Product 1", Price = 15.00m },
                        new { Id = 2, Name = "Product 2", Price = 20.00m },
                        new { Id = 3, Name = "Product 3", Price = 25.00m },
                        new { Id = 4, Name = "Product 4", Price = 30.00m },
                        new { Id = 5, Name = "Product 5", Price = 35.00m },
                        new { Id = 6, Name = "Product 6", Price = 40.00m },
                        new { Id = 7, Name = "Product 7", Price = 45.00m },
                        new { Id = 8, Name = "Product 8", Price = 50.00m },
                        new { Id = 9, Name = "Product 9", Price = 55.00m },
                        new { Id = 10, Name = "Product 10", Price = 60.00m },
                        new { Id = 11, Name = "Product 11", Price = 65.00m },
                        new { Id = 12, Name = "Product 12", Price = 70.00m },
                        new { Id = 13, Name = "Product 13", Price = 75.00m },
                        new { Id = 14, Name = "Product 14", Price = 80.00m },
                        new { Id = 15, Name = "Product 15", Price = 85.00m },
                        new { Id = 16, Name = "Product 16", Price = 90.00m },
                        new { Id = 17, Name = "Product 17", Price = 95.00m },
                        new { Id = 18, Name = "Product 18", Price = 100.00m },
                        new { Id = 19, Name = "Product 19", Price = 105.00m },
                        new { Id = 20, Name = "Product 20", Price = 110.00m },
                        new { Id = 21, Name = "Product 21", Price = 115.00m },
                        new { Id = 22, Name = "Product 22", Price = 120.00m },
                        new { Id = 23, Name = "Product 23", Price = 125.00m },
                        new { Id = 24, Name = "Product 24", Price = 130.00m },
                        new { Id = 25, Name = "Product 25", Price = 135.00m },
                        new { Id = 26, Name = "Product 26", Price = 140.00m },
                        new { Id = 27, Name = "Product 27", Price = 145.00m },
                        new { Id = 28, Name = "Product 28", Price = 150.00m },
                        new { Id = 29, Name = "Product 29", Price = 155.00m },
                        new { Id = 30, Name = "Product 30", Price = 160.00m });
                });
#pragma warning restore 612, 618
        }
    }
}
