// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305050041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Department = "IT",
                            Email = "employee1@company.com",
                            EmployeeName = "Employee 1",
                            JoiningDate = new DateTime(2026, 2, 23, 10, 30, 40, 402, DateTimeKind.Local).AddTicks(6058),
                            PhoneNumber = "+1-555-1001",
                            Position = "Manager",
                            Salary = 51000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            Department = "HR",
                            Email = "employee2@company.com",
                            EmployeeName = "Employee 2",
                            JoiningDate = new DateTime(2026, 2, 13, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7717),
                            PhoneNumber = "+1-555-1002",
                            Position = "Developer",
                            Salary = 52000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            Department = "Finance",
                            Email = "employee3@company.com",
                            EmployeeName = "Employee 3",
                            JoiningDate = new DateTime(2026, 2, 3, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7736),
                            PhoneNumber = "+1-555-1003",
                            Position = "Analyst",
                            Salary = 53000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            Department = "Sales",
                            Email = "employee4@company.com",
                            EmployeeName = "Employee 4",
                            JoiningDate = new DateTime(2026, 1, 24, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7739),
                            PhoneNumber = "+1-555-1004",
                            Position = "Coordinator",
                            Salary = 54000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            Department = "Marketing",
                            Email = "employee5@company.com",
                            EmployeeName = "Employee 5",
                            JoiningDate = new DateTime(2026, 1, 14, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7743),
                            PhoneNumber = "+1-555-1005",
                            Position = "Specialist",
                            Salary = 55000m
                        },
                        new
                        {
                            EmployeeId = 6,
                            Department = "Operations",
                            Email = "employee6@company.com",
                            EmployeeName = "Employee 6",
                            JoiningDate = new DateTime(2026, 1, 4, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7752),
                            PhoneNumber = "+1-555-1006",
                            Position = "Associate",
                            Salary = 56000m
                        },
                        new
                        {
                            EmployeeId = 7,
                            Department = "IT",
                            Email = "employee7@company.com",
                            EmployeeName = "Employee 7",
                            JoiningDate = new DateTime(2025, 12, 25, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7755),
                            PhoneNumber = "+1-555-1007",
                            Position = "Manager",
                            Salary = 57000m
                        },
                        new
                        {
                            EmployeeId = 8,
                            Department = "HR",
                            Email = "employee8@company.com",
                            EmployeeName = "Employee 8",
                            JoiningDate = new DateTime(2025, 12, 15, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7757),
                            PhoneNumber = "+1-555-1008",
                            Position = "Developer",
                            Salary = 58000m
                        },
                        new
                        {
                            EmployeeId = 9,
                            Department = "Finance",
                            Email = "employee9@company.com",
                            EmployeeName = "Employee 9",
                            JoiningDate = new DateTime(2025, 12, 5, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7760),
                            PhoneNumber = "+1-555-1009",
                            Position = "Analyst",
                            Salary = 59000m
                        },
                        new
                        {
                            EmployeeId = 10,
                            Department = "Sales",
                            Email = "employee10@company.com",
                            EmployeeName = "Employee 10",
                            JoiningDate = new DateTime(2025, 11, 25, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7764),
                            PhoneNumber = "+1-555-1010",
                            Position = "Coordinator",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 11,
                            Department = "Marketing",
                            Email = "employee11@company.com",
                            EmployeeName = "Employee 11",
                            JoiningDate = new DateTime(2025, 11, 15, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7767),
                            PhoneNumber = "+1-555-1011",
                            Position = "Specialist",
                            Salary = 61000m
                        },
                        new
                        {
                            EmployeeId = 12,
                            Department = "Operations",
                            Email = "employee12@company.com",
                            EmployeeName = "Employee 12",
                            JoiningDate = new DateTime(2025, 11, 5, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7769),
                            PhoneNumber = "+1-555-1012",
                            Position = "Associate",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 13,
                            Department = "IT",
                            Email = "employee13@company.com",
                            EmployeeName = "Employee 13",
                            JoiningDate = new DateTime(2025, 10, 26, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7772),
                            PhoneNumber = "+1-555-1013",
                            Position = "Manager",
                            Salary = 63000m
                        },
                        new
                        {
                            EmployeeId = 14,
                            Department = "HR",
                            Email = "employee14@company.com",
                            EmployeeName = "Employee 14",
                            JoiningDate = new DateTime(2025, 10, 16, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7774),
                            PhoneNumber = "+1-555-1014",
                            Position = "Developer",
                            Salary = 64000m
                        },
                        new
                        {
                            EmployeeId = 15,
                            Department = "Finance",
                            Email = "employee15@company.com",
                            EmployeeName = "Employee 15",
                            JoiningDate = new DateTime(2025, 10, 6, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7777),
                            PhoneNumber = "+1-555-1015",
                            Position = "Analyst",
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 16,
                            Department = "Sales",
                            Email = "employee16@company.com",
                            EmployeeName = "Employee 16",
                            JoiningDate = new DateTime(2025, 9, 26, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7780),
                            PhoneNumber = "+1-555-1016",
                            Position = "Coordinator",
                            Salary = 66000m
                        },
                        new
                        {
                            EmployeeId = 17,
                            Department = "Marketing",
                            Email = "employee17@company.com",
                            EmployeeName = "Employee 17",
                            JoiningDate = new DateTime(2025, 9, 16, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7782),
                            PhoneNumber = "+1-555-1017",
                            Position = "Specialist",
                            Salary = 67000m
                        },
                        new
                        {
                            EmployeeId = 18,
                            Department = "Operations",
                            Email = "employee18@company.com",
                            EmployeeName = "Employee 18",
                            JoiningDate = new DateTime(2025, 9, 6, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7786),
                            PhoneNumber = "+1-555-1018",
                            Position = "Associate",
                            Salary = 68000m
                        },
                        new
                        {
                            EmployeeId = 19,
                            Department = "IT",
                            Email = "employee19@company.com",
                            EmployeeName = "Employee 19",
                            JoiningDate = new DateTime(2025, 8, 27, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7788),
                            PhoneNumber = "+1-555-1019",
                            Position = "Manager",
                            Salary = 69000m
                        },
                        new
                        {
                            EmployeeId = 20,
                            Department = "HR",
                            Email = "employee20@company.com",
                            EmployeeName = "Employee 20",
                            JoiningDate = new DateTime(2025, 8, 17, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7791),
                            PhoneNumber = "+1-555-1020",
                            Position = "Developer",
                            Salary = 70000m
                        },
                        new
                        {
                            EmployeeId = 21,
                            Department = "Finance",
                            Email = "employee21@company.com",
                            EmployeeName = "Employee 21",
                            JoiningDate = new DateTime(2025, 8, 7, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7793),
                            PhoneNumber = "+1-555-1021",
                            Position = "Analyst",
                            Salary = 71000m
                        },
                        new
                        {
                            EmployeeId = 22,
                            Department = "Sales",
                            Email = "employee22@company.com",
                            EmployeeName = "Employee 22",
                            JoiningDate = new DateTime(2025, 7, 28, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7796),
                            PhoneNumber = "+1-555-1022",
                            Position = "Coordinator",
                            Salary = 72000m
                        },
                        new
                        {
                            EmployeeId = 23,
                            Department = "Marketing",
                            Email = "employee23@company.com",
                            EmployeeName = "Employee 23",
                            JoiningDate = new DateTime(2025, 7, 18, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7822),
                            PhoneNumber = "+1-555-1023",
                            Position = "Specialist",
                            Salary = 73000m
                        },
                        new
                        {
                            EmployeeId = 24,
                            Department = "Operations",
                            Email = "employee24@company.com",
                            EmployeeName = "Employee 24",
                            JoiningDate = new DateTime(2025, 7, 8, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7825),
                            PhoneNumber = "+1-555-1024",
                            Position = "Associate",
                            Salary = 74000m
                        },
                        new
                        {
                            EmployeeId = 25,
                            Department = "IT",
                            Email = "employee25@company.com",
                            EmployeeName = "Employee 25",
                            JoiningDate = new DateTime(2025, 6, 28, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7828),
                            PhoneNumber = "+1-555-1025",
                            Position = "Manager",
                            Salary = 75000m
                        },
                        new
                        {
                            EmployeeId = 26,
                            Department = "HR",
                            Email = "employee26@company.com",
                            EmployeeName = "Employee 26",
                            JoiningDate = new DateTime(2025, 6, 18, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7831),
                            PhoneNumber = "+1-555-1026",
                            Position = "Developer",
                            Salary = 76000m
                        },
                        new
                        {
                            EmployeeId = 27,
                            Department = "Finance",
                            Email = "employee27@company.com",
                            EmployeeName = "Employee 27",
                            JoiningDate = new DateTime(2025, 6, 8, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7833),
                            PhoneNumber = "+1-555-1027",
                            Position = "Analyst",
                            Salary = 77000m
                        },
                        new
                        {
                            EmployeeId = 28,
                            Department = "Sales",
                            Email = "employee28@company.com",
                            EmployeeName = "Employee 28",
                            JoiningDate = new DateTime(2025, 5, 29, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7836),
                            PhoneNumber = "+1-555-1028",
                            Position = "Coordinator",
                            Salary = 78000m
                        },
                        new
                        {
                            EmployeeId = 29,
                            Department = "Marketing",
                            Email = "employee29@company.com",
                            EmployeeName = "Employee 29",
                            JoiningDate = new DateTime(2025, 5, 19, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7838),
                            PhoneNumber = "+1-555-1029",
                            Position = "Specialist",
                            Salary = 79000m
                        },
                        new
                        {
                            EmployeeId = 30,
                            Department = "Operations",
                            Email = "employee30@company.com",
                            EmployeeName = "Employee 30",
                            JoiningDate = new DateTime(2025, 5, 9, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7841),
                            PhoneNumber = "+1-555-1030",
                            Position = "Associate",
                            Salary = 80000m
                        },
                        new
                        {
                            EmployeeId = 31,
                            Department = "IT",
                            Email = "employee31@company.com",
                            EmployeeName = "Employee 31",
                            JoiningDate = new DateTime(2025, 4, 29, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7843),
                            PhoneNumber = "+1-555-1031",
                            Position = "Manager",
                            Salary = 81000m
                        },
                        new
                        {
                            EmployeeId = 32,
                            Department = "HR",
                            Email = "employee32@company.com",
                            EmployeeName = "Employee 32",
                            JoiningDate = new DateTime(2025, 4, 19, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7846),
                            PhoneNumber = "+1-555-1032",
                            Position = "Developer",
                            Salary = 82000m
                        },
                        new
                        {
                            EmployeeId = 33,
                            Department = "Finance",
                            Email = "employee33@company.com",
                            EmployeeName = "Employee 33",
                            JoiningDate = new DateTime(2025, 4, 9, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7848),
                            PhoneNumber = "+1-555-1033",
                            Position = "Analyst",
                            Salary = 83000m
                        },
                        new
                        {
                            EmployeeId = 34,
                            Department = "Sales",
                            Email = "employee34@company.com",
                            EmployeeName = "Employee 34",
                            JoiningDate = new DateTime(2025, 3, 30, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7852),
                            PhoneNumber = "+1-555-1034",
                            Position = "Coordinator",
                            Salary = 84000m
                        },
                        new
                        {
                            EmployeeId = 35,
                            Department = "Marketing",
                            Email = "employee35@company.com",
                            EmployeeName = "Employee 35",
                            JoiningDate = new DateTime(2025, 3, 20, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7855),
                            PhoneNumber = "+1-555-1035",
                            Position = "Specialist",
                            Salary = 85000m
                        },
                        new
                        {
                            EmployeeId = 36,
                            Department = "Operations",
                            Email = "employee36@company.com",
                            EmployeeName = "Employee 36",
                            JoiningDate = new DateTime(2025, 3, 10, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7857),
                            PhoneNumber = "+1-555-1036",
                            Position = "Associate",
                            Salary = 86000m
                        },
                        new
                        {
                            EmployeeId = 37,
                            Department = "IT",
                            Email = "employee37@company.com",
                            EmployeeName = "Employee 37",
                            JoiningDate = new DateTime(2025, 2, 28, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7859),
                            PhoneNumber = "+1-555-1037",
                            Position = "Manager",
                            Salary = 87000m
                        },
                        new
                        {
                            EmployeeId = 38,
                            Department = "HR",
                            Email = "employee38@company.com",
                            EmployeeName = "Employee 38",
                            JoiningDate = new DateTime(2025, 2, 18, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7862),
                            PhoneNumber = "+1-555-1038",
                            Position = "Developer",
                            Salary = 88000m
                        },
                        new
                        {
                            EmployeeId = 39,
                            Department = "Finance",
                            Email = "employee39@company.com",
                            EmployeeName = "Employee 39",
                            JoiningDate = new DateTime(2025, 2, 8, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7865),
                            PhoneNumber = "+1-555-1039",
                            Position = "Analyst",
                            Salary = 89000m
                        },
                        new
                        {
                            EmployeeId = 40,
                            Department = "Sales",
                            Email = "employee40@company.com",
                            EmployeeName = "Employee 40",
                            JoiningDate = new DateTime(2025, 1, 29, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7867),
                            PhoneNumber = "+1-555-1040",
                            Position = "Coordinator",
                            Salary = 90000m
                        },
                        new
                        {
                            EmployeeId = 41,
                            Department = "Marketing",
                            Email = "employee41@company.com",
                            EmployeeName = "Employee 41",
                            JoiningDate = new DateTime(2025, 1, 19, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7870),
                            PhoneNumber = "+1-555-1041",
                            Position = "Specialist",
                            Salary = 91000m
                        },
                        new
                        {
                            EmployeeId = 42,
                            Department = "Operations",
                            Email = "employee42@company.com",
                            EmployeeName = "Employee 42",
                            JoiningDate = new DateTime(2025, 1, 9, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7872),
                            PhoneNumber = "+1-555-1042",
                            Position = "Associate",
                            Salary = 92000m
                        },
                        new
                        {
                            EmployeeId = 43,
                            Department = "IT",
                            Email = "employee43@company.com",
                            EmployeeName = "Employee 43",
                            JoiningDate = new DateTime(2024, 12, 30, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7875),
                            PhoneNumber = "+1-555-1043",
                            Position = "Manager",
                            Salary = 93000m
                        },
                        new
                        {
                            EmployeeId = 44,
                            Department = "HR",
                            Email = "employee44@company.com",
                            EmployeeName = "Employee 44",
                            JoiningDate = new DateTime(2024, 12, 20, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7878),
                            PhoneNumber = "+1-555-1044",
                            Position = "Developer",
                            Salary = 94000m
                        },
                        new
                        {
                            EmployeeId = 45,
                            Department = "Finance",
                            Email = "employee45@company.com",
                            EmployeeName = "Employee 45",
                            JoiningDate = new DateTime(2024, 12, 10, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7880),
                            PhoneNumber = "+1-555-1045",
                            Position = "Analyst",
                            Salary = 95000m
                        },
                        new
                        {
                            EmployeeId = 46,
                            Department = "Sales",
                            Email = "employee46@company.com",
                            EmployeeName = "Employee 46",
                            JoiningDate = new DateTime(2024, 11, 30, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7882),
                            PhoneNumber = "+1-555-1046",
                            Position = "Coordinator",
                            Salary = 96000m
                        },
                        new
                        {
                            EmployeeId = 47,
                            Department = "Marketing",
                            Email = "employee47@company.com",
                            EmployeeName = "Employee 47",
                            JoiningDate = new DateTime(2024, 11, 20, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7885),
                            PhoneNumber = "+1-555-1047",
                            Position = "Specialist",
                            Salary = 97000m
                        },
                        new
                        {
                            EmployeeId = 48,
                            Department = "Operations",
                            Email = "employee48@company.com",
                            EmployeeName = "Employee 48",
                            JoiningDate = new DateTime(2024, 11, 10, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7888),
                            PhoneNumber = "+1-555-1048",
                            Position = "Associate",
                            Salary = 98000m
                        },
                        new
                        {
                            EmployeeId = 49,
                            Department = "IT",
                            Email = "employee49@company.com",
                            EmployeeName = "Employee 49",
                            JoiningDate = new DateTime(2024, 10, 31, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7890),
                            PhoneNumber = "+1-555-1049",
                            Position = "Manager",
                            Salary = 99000m
                        },
                        new
                        {
                            EmployeeId = 50,
                            Department = "HR",
                            Email = "employee50@company.com",
                            EmployeeName = "Employee 50",
                            JoiningDate = new DateTime(2024, 10, 21, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7892),
                            PhoneNumber = "+1-555-1050",
                            Position = "Developer",
                            Salary = 100000m
                        },
                        new
                        {
                            EmployeeId = 51,
                            Department = "Finance",
                            Email = "employee51@company.com",
                            EmployeeName = "Employee 51",
                            JoiningDate = new DateTime(2024, 10, 11, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7895),
                            PhoneNumber = "+1-555-1051",
                            Position = "Analyst",
                            Salary = 101000m
                        },
                        new
                        {
                            EmployeeId = 52,
                            Department = "Sales",
                            Email = "employee52@company.com",
                            EmployeeName = "Employee 52",
                            JoiningDate = new DateTime(2024, 10, 1, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7898),
                            PhoneNumber = "+1-555-1052",
                            Position = "Coordinator",
                            Salary = 102000m
                        },
                        new
                        {
                            EmployeeId = 53,
                            Department = "Marketing",
                            Email = "employee53@company.com",
                            EmployeeName = "Employee 53",
                            JoiningDate = new DateTime(2024, 9, 21, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7908),
                            PhoneNumber = "+1-555-1053",
                            Position = "Specialist",
                            Salary = 103000m
                        },
                        new
                        {
                            EmployeeId = 54,
                            Department = "Operations",
                            Email = "employee54@company.com",
                            EmployeeName = "Employee 54",
                            JoiningDate = new DateTime(2024, 9, 11, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7911),
                            PhoneNumber = "+1-555-1054",
                            Position = "Associate",
                            Salary = 104000m
                        },
                        new
                        {
                            EmployeeId = 55,
                            Department = "IT",
                            Email = "employee55@company.com",
                            EmployeeName = "Employee 55",
                            JoiningDate = new DateTime(2024, 9, 1, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7914),
                            PhoneNumber = "+1-555-1055",
                            Position = "Manager",
                            Salary = 105000m
                        },
                        new
                        {
                            EmployeeId = 56,
                            Department = "HR",
                            Email = "employee56@company.com",
                            EmployeeName = "Employee 56",
                            JoiningDate = new DateTime(2024, 8, 22, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7916),
                            PhoneNumber = "+1-555-1056",
                            Position = "Developer",
                            Salary = 106000m
                        },
                        new
                        {
                            EmployeeId = 57,
                            Department = "Finance",
                            Email = "employee57@company.com",
                            EmployeeName = "Employee 57",
                            JoiningDate = new DateTime(2024, 8, 12, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7919),
                            PhoneNumber = "+1-555-1057",
                            Position = "Analyst",
                            Salary = 107000m
                        },
                        new
                        {
                            EmployeeId = 58,
                            Department = "Sales",
                            Email = "employee58@company.com",
                            EmployeeName = "Employee 58",
                            JoiningDate = new DateTime(2024, 8, 2, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7921),
                            PhoneNumber = "+1-555-1058",
                            Position = "Coordinator",
                            Salary = 108000m
                        },
                        new
                        {
                            EmployeeId = 59,
                            Department = "Marketing",
                            Email = "employee59@company.com",
                            EmployeeName = "Employee 59",
                            JoiningDate = new DateTime(2024, 7, 23, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7924),
                            PhoneNumber = "+1-555-1059",
                            Position = "Specialist",
                            Salary = 109000m
                        },
                        new
                        {
                            EmployeeId = 60,
                            Department = "Operations",
                            Email = "employee60@company.com",
                            EmployeeName = "Employee 60",
                            JoiningDate = new DateTime(2024, 7, 13, 10, 30, 40, 403, DateTimeKind.Local).AddTicks(7926),
                            PhoneNumber = "+1-555-1060",
                            Position = "Associate",
                            Salary = 110000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
