// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHostelAPI.Data;

#nullable disable

namespace jwtapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311084350_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentHostelAPI.Models.Hostel", b =>
                {
                    b.Property<int>("HostelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostelId"));

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("HostelId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Hostels");

                    b.HasData(
                        new
                        {
                            HostelId = 1,
                            RoomNumber = "A101",
                            StudentId = 1
                        },
                        new
                        {
                            HostelId = 2,
                            RoomNumber = "B202",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("StudentHostelAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Age = 20,
                            Name = "Alice"
                        },
                        new
                        {
                            StudentId = 2,
                            Age = 22,
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("StudentHostelAPI.Models.Hostel", b =>
                {
                    b.HasOne("StudentHostelAPI.Models.Student", "Student")
                        .WithOne("Hostel")
                        .HasForeignKey("StudentHostelAPI.Models.Hostel", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHostelAPI.Models.Student", b =>
                {
                    b.Navigation("Hostel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
