# Generated by Django 4.2.7 on 2025-11-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('crack', 'Crack'), ('pothole', 'Pothole'), ('rough_surface', 'Rough Surface'), ('alligator_crack', 'Alligator Crack'), ('edge_crack', 'Edge Crack'), ('joint_crack', 'Joint Crack'), ('no_defect', 'No Defect')], max_length=50)),
                ('severity_score', models.FloatField(help_text='Severity score from 0 to 100')),
                ('condition_label', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('ai_confidence', models.FloatField(help_text='AI model confidence score (0-1)')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated_images/%Y/%m/%d/')),
                ('model_name', models.CharField(default='DefaultModel', max_length=100)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict)),
                ('maintenance_suggestion', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.imagerecord')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
