FROM node:18 AS base
WORKDIR /app
FROM base AS builder
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
COPY . .
RUN npm run build

FROM base AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json .
COPY --from=builder /app/tsconfig.json .
RUN npm i --omit=dev
RUN npm cache clean --force
EXPOSE 3000
CMD [ "node","dist/index.js" ]