version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - nginx_data:/usr/share/nginx/html
    networks:
      - my_network
    environment:
      - NGINX_PORT=80   # variable corrected

  alpine:
    image: alpine:latest
    container_name: alpine_container
    volumes:
      - alpine_data:/data
    networks:
      - my_network
  redis:
    image: redis:latest
    container_name: redis_server
    volumes: 
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my_network
volumes:
  nginx_data:
  alpine_data:
  redis_data:
networks:
  my_network:
    driver: bridge